### ISSUE TITLE
Hardcoded ip in setenv.sh ?

### ISSUE THREAD

**Issue by gururaj0** [DirkNachbar/Docker#5]
why hardcoded ip ?

# Repository Connect
--

export DC_DB_HOST=172.17.0.1
--

**Comment by gururaj0** [comment]
As a result of that..I changed it to 0.0.0.0 to match the Oracle DB container.


root@docker-forms-ubuntu:/opt/oracle/oradata# docker ps                                                                                                                                             CONTAINER ID        IMAGE                         COMMAND                  CREATED             STATUS                    PORTS                                                      NAMES           19fabdd4d629        oracle/database:12.2.0.1-ee   "/bin/sh -c 'exec $O…"   41 minutes ago      Up 41 minutes (healthy)   0.0.0.0:1521->1521/tcp, 0.0.0.0:8080->8080/tcp, 5500/tcp   oraclecontainer
--

Error when running  --> docker-compose up -d frfmw; docker logs frfmw -f


Aug 23, 2019 12:35:34 AM oracle.security.jps.internal.policystore.util.JpsDataManagerUtil getDBConnection                                                                                        WARNING: Can not connect DB with URL jdbc:oracle:thin:@//0.0.0.0:1521/ORCLPDB                                                                                                                    java.sql.SQLRecoverableException: IO Error: The Network Adapter could not establish the connection                                                                                                       at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:774)                                                                                                                                at oracle.jdbc.driver.PhysicalConnection.connect(PhysicalConnection.java:702)                                                                                                                    at oracle.jdbc.driver.T4CDriverExtension.getConnection(T4CDriverExtension.java:39)                                                                                                               at oracle.jdbc.driver.OracleDriver.connect(OracleDriver.java:691)                                                                                                                                at java.sql.DriverManager.getConnection(DriverManager.java:664)                                                                                                                                  at java.sql.DriverManager.getConnection(DriverManager.java:247)                                                                                                                                  at oracle.security.jps.internal.policystore.util.JpsDataManagerUtil.getDBConnection(JpsDataManagerUtil.java:400)                                                                                 at oracle.security.jps.internal.policystore.util.JpsDataManagerUtil.isNewSchema(JpsDataManagerUtil.java:249)                                                                                     at oracle.security.jps.internal.core.datamanager.DataManagerFactoryImpl.isNewSchema(DataManagerFactoryImpl.java:252)                                                                             at oracle.security.jps.internal.common.rdbms.util.JpsDbBootstrapImpl.(JpsDbBootstrapImpl.java:182)                                                                                         at oracle.security.opss.tools.lifecycle.OpssLifecycleUtil.getJpsDbBootstrap(OpssLifecycleUtil.java:784)                                                                                          at oracle.security.opss.tools.lifecycle.OpssLifecycleUtil.checkIfFarmExists(OpssLifecycleUtil.java:706)                                                                                          at oracle.security.opss.tools.lifecycle.OpssDomainConfigImpl.checkIfFarmExists(OpssDomainConfigImpl.java:907)                                                                                    at oracle.security.opss.tools.lifecycle.OpssDomainConfigImpl.configureDBSecurityStore(OpssDomainConfigImpl.java:600)                                                                             at oracle.security.opss.tools.lifecycle.OpssDomainConfigImpl.configureSubsystem(OpssDomainConfigImpl.java:489)                                                                                   at oracle.security.opss.tools.lifecycle.OpssDomainConfigImpl.initializeSubsystem(OpssDomainConfigImpl.java:269)                                                                                  at oracle.security.opss.tools.lifecycle.cie.OpssSecurityConfiguration.initializeSubsystem(OpssSecurityConfiguration.java:188)                                                                    at com.oracle.cie.domain.progress.template.importer.ImporterOPSSProcessingPhase.initialize(ImporterOPSSProcessingPhase.java:36)                                                                  at com.oracle.cie.domain.progress.domain.generation.OPSSProcessingPhase.processOPSS(OPSSProcessingPhase.java:154)                                                                                at com.oracle.cie.domain.progress.domain.generation.OPSSProcessingPhase.execute(OPSSProcessingPhase.java:54)                                                                                     at com.oracle.cie.domain.progress.AbstractProgressGenerator.run(AbstractProgressGenerator.java:94)                                                                                               at java.lang.Thread.run(Thread.java:748)                                                                                                                                                 Caused by: oracle.net.ns.NetException: The Network Adapter could not establish the connection                                                                                                            at oracle.net.nt.ConnStrategy.execute(ConnStrategy.java:523)                                                                                                                                     at oracle.net.resolver.AddrResolution.resolveAndExecute(AddrResolution.java:521)                                                                                                                 at oracle.net.ns.NSProtocol.establishConnection(NSProtocol.java:660)                                                                                                                             at oracle.net.ns.NSProtocol.connect(NSProtocol.java:286)                                                                                                                                         at oracle.jdbc.driver.T4CConnection.connect(T4CConnection.java:1438)                                                                                                                             at oracle.jdbc.driver.T4CConnection.logon(T4CConnection.java:518)                                                                                                                                ... 21 more                                                                                                                                                                              Caused by: java.io.IOException: Connection refused, socket connect lapse 8 ms. /0.0.0.0 1521 0 1 true                                                                                                    at oracle.net.nt.TcpNTAdapter.connect(TcpNTAdapter.java:209)                                                                                                                                     at oracle.net.nt.ConnOption.connect(ConnOption.java:161)                                                                                                                                         at oracle.net.nt.ConnStrategy.execute(ConnStrategy.java:470)                                                                                                                                     ... 26 more                                                                                                                                                                              Caused by: java.net.ConnectException: Connection refused                                                                                                                                                 at sun.nio.ch.Net.connect0(Native Method)                                                                                                                                                        at sun.nio.ch.Net.connect(Net.java:454)                                                                                                                                                          at sun.nio.ch.Net.connect(Net.java:446)                                                                                                                                                          at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:648)                                                                                                                              at java.nio.channels.SocketChannel.open(SocketChannel.java:189)                                                                                                                                  at oracle.net.nt.TimeoutSocketChannel.(TimeoutSocketChannel.java:81)                                                                                                                       at oracle.net.nt.TcpNTAdapter.connect(TcpNTAdapter.java:169)                                                                                                                                     ... 28 more
--
